on:
  push:
    branches:
      - main
  pull_request:

name: coverage

permissions:
  contents: read
  code-quality: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Generate coverage report
        run: |
          cargo install cargo-tarpaulin --locked
          cargo tarpaulin --ciserver github-ci --out Xml

      - name: Upload coverage report to GitHub
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@82c7aee3fb2ad768e00b00a0a8d749c5815085b6 # v1
        with:
          file: cobertura.xml
          language: Rust
          label: code-coverage/tarpaulin
