name: coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: codecov

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Generate coverage report
        run: |
          cargo install cargo-tarpaulin --locked
          cargo tarpaulin --ciserver github-ci --out Xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
