on:
  push:
    branches:
      - main
  pull_request:

name: lint

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-targets -- -D warnings
