on:
  push:
    branches:
      - main
  pull_request:

name: lint

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Rust
        run: |
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt clippy

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-targets -- -D warnings
